(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

(require 'init-pkg)
(require 'init-ui)
(require 'init-indent)
(require 'init-minibuffer)
(require 'init-misc)
(require 'init-evil)
(require 'init-paredit)
(require 'init-lsp)
(require 'init-which)
(require 'init-completion)
(require 'init-command)
(require 'init-keymap)
(require 'init-org)
